### ISSUE TITLE
error running rake binary:all

### ISSUE THREAD

**Issue by cornu-ammonis** [sqreen/ruby-libv8-node#17]
I get this error when running the command
```
TypeError: no implicit conversion of nil into String
/Users/andrewjones/Documents/projects/aha/ruby-libv8-node/Rakefile:63:in `read'
```

Am I missing some step to have contents at `src/node-v`...

@lloeki Would very much appreciate guidance on how to get this workflow running - I am testing out the capability of publishing a forked version of this gem with node v16 v8 - thanks!

**Comment by lloeki** [comment]
Yeah I really need to put some README, BUILDING, and CONTRIBUTING files up. FYI `rake binary:all` is only for macOS, to package all compatible gems.

The steps to build don't require rake (on purpose, otherwise it creates a dependency on Gemfile/gemspec and that flies in the face of Docker layers), they're in `.github/workflows/something.yml` though, as well as in Ruby in the ext dir:

```
./libexec/download-node 16.0.0
./libexec/extract-node 16.0.0
./libexec/build-libv8 16.0.0
./libexec/build-monolith 16.0.0
./libexec/inject-libv8 16.0.0
bundle exec rake binary:all
```

Anyway `rake binary` should have done the steps, unless I forgot to update a path (I moved from magic github repo tarballs to the official tarball releases, which added a `v` in the name).
